@extends('layouts.customer')
@section('title', 'E-Ticket')
@section('content')
<div class="max-w-5xl mx-auto space-y-6">
<div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold text-white">E-Ticket</h2><p class="text-zinc-500 text-sm">{{ $booking->passengers->count() }} passenger ticket(s)</p></div><a href="{{ route('customer.eticket.pdf', $booking) }}" class="px-5 py-2.5 bg-amber-500 text-black rounded-xl font-semibold text-sm"><i class="fas fa-file-pdf mr-2"></i>Download PDF</a></div>
<div class="bg-white rounded-xl overflow-hidden">
<div class="bg-amber-500 p-7 flex justify-between"><div><h2 class="text-2xl font-bold text-black">LUXURYFLY</h2><p class="text-black/70">Official Multi-Passenger E-Ticket</p></div><div class="text-right font-mono font-bold text-black">{{ $booking->booking_code }}</div></div>
<div class="p-7 space-y-7">
<div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-black"><div><small class="text-zinc-500">AIRLINE</small><p class="font-semibold">{{ $booking->flight->airline->name }}</p><p>{{ $booking->flight->flight_number }}</p></div><div><small class="text-zinc-500">AIRCRAFT</small><p class="font-semibold">{{ $booking->flight->airplane->model ?? '-' }}</p></div><div><small class="text-zinc-500">DEPARTURE</small><p class="font-semibold">{{ $booking->flight->departure_time->format('d M Y H:i') }}</p></div><div><small class="text-zinc-500">CLASS</small><p class="font-semibold">{{ $booking->cabin_class_label }}</p><p class="text-emerald-600">{{ strtoupper($booking->status) }}</p></div></div>
<div class="py-6 border-y-2 border-dashed border-zinc-200 flex justify-between text-black"><div class="text-center"><p class="text-3xl font-bold">{{ $booking->flight->departureAirport->iata_code }}</p><p>{{ $booking->flight->departureAirport->city }}</p></div><i class="fas fa-plane text-amber-500 self-center"></i><div class="text-center"><p class="text-3xl font-bold">{{ $booking->flight->arrivalAirport->iata_code }}</p><p>{{ $booking->flight->arrivalAirport->city }}</p></div></div>
<div class="overflow-x-auto"><h3 class="text-black font-semibold mb-3">Passenger Details</h3><table class="w-full min-w-[760px]"><thead><tr class="text-left text-xs text-zinc-500"><th class="pb-2">NO</th><th>NAME</th><th>GENDER</th><th>BIRTH DATE</th><th>SEAT</th><th>NATIONALITY</th><th>PASSPORT</th></tr></thead><tbody class="divide-y divide-zinc-100">@foreach($booking->passengers as $index => $passenger)<tr class="text-sm text-black"><td class="py-3">{{ $index + 1 }}</td><td>{{ $passenger->full_name }}</td><td>{{ $passenger->gender_label }}</td><td>{{ optional($passenger->resolved_date_of_birth)->format('d M Y') ?? '-' }}</td><td class="font-mono text-amber-700">{{ $passenger->resolved_seat_number }}</td><td>{{ $passenger->nationality ?? '-' }}</td><td>{{ $passenger->passport_number ?? '-' }}</td></tr>@endforeach</tbody></table></div>
<div class="pt-5 border-t flex justify-between text-black"><div>Passengers: <strong>{{ $booking->total_passengers }}</strong></div><div>Total: <strong class="text-amber-600">Rp {{ number_format($booking->total_price,0,',','.') }}</strong></div><div>Payment: <strong class="text-emerald-600">{{ strtoupper($booking->payment->payment_status ?? 'paid') }}</strong></div></div>
</div></div></div>
@endsection
